### ISSUE TITLE
Allow to specify output directory

### ISSUE THREAD

**Issue by felixfbecker** [DonJayamanne/javaVSCode#1]
I have my source files in `src` and my class files in `bin`

**Comment by mfs409** [comment]
I'm in the same situation as @felixfbecker... I'd like to use this with a maven project, where the source files are in /src/..., and the outputs are in /target.  If I set cwd (launch.json) to "${workspaceRoot}/target/classes/", and I also use "\"$(workspaceRoot}/target/classes;\"" as the "-cp" option, then pressing F5 works... but during debug, I get the message "Source \App.java is not available".  I can still run the program, complete with watchpoints and breakpoints... I just can't see the source while debugging.

Would it be easier to add a srcdir field to launch.json, so that the plugin knew where to find the code?  That way, the existing functionality wouldn't need to be redone, you could just look at another place in the launch.json to figure out the prefix for files to display during debugging.

Update: Could this be as simple as providing a field in launch.json that gets passed to jdb as the sourcepath?

**Comment by mfs409** [comment]
I've confirmed that when the jdb command is run in the shell, providing a sourcepath solves the problem.  But pushing a sourcepath into the args in jdb.ts initProc line 134 doesn't seem to be helping, even when I hard-code a full path that I know works when connecting jdb to a running Java process on the command line.

**Comment by mfs409** [comment]
@felixfbecker 
With the following launch.json, I am able to run with a maven project:

{
    "version": "0.2.0",
    "configurations": [
        {
            "jdkPath": "c:/Program Files/Java/jdk1.8.0_77/bin",
            "name": "Java",
            "type": "java",
            "request": "launch",
            "stopOnEntry": true,
            "cwd": "${workspaceRoot}/src/main/java/",
            "startupClass": "com.me.my.App",
            "options": [
                "-classpath",
                "${workspaceRoot}/target/classes"
            ]
        }
    ]
}

If the current working directory is where your source files are, and the location of your class files is specified in the classpath in the options, it works (at least for my test cases).

**Comment by DonJayamanne** [comment]
Sorry for the silence guys, will look into this soon.

**Comment by DonJayamanne** [comment]
@mfs409 , @felixfbecker 
Does the final solution proposed by @mfs409 work? Or do we need a better configuration setup. I'm inclined to believe that we don't.
Apologies for the silence in this space.

**Comment by faustinoaq** [comment]
@DonJayamanne I use javaVSCode in Manjaro Linux and the current setup with the solution proposed by @mfs409 works fine for me :+1: 
Only I have breakpoints problems when packages exist #16
BTW, @DonJayamanne thanks for _javaVSCode_
Bye :raising_hand_man:

**Comment by tcsx** [comment]
@DonJayamanne  The final solution proposed by @mfs409 works, thanks👍
However, I think it would be nicer if we don't have to type package names for "startupClass", so that we can just use the generic "${fileBasename}" , instead of having to change the package names manually every time we use a file from a different package.
